### ISSUE TITLE
Schedule First SeaGL 2021 Code of Conduct Meeting

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#121]
This may have already occurred, but creating an issue for each committee to verify that the ball is rolling!

**Comment by koronkowy** [comment]
At minimum, if no committee if formed in time for the 2021 conference.. these two things should be addressed:
- https://github.com/SeaGL/organization/issues/176 update CoC page with 2021 specific wording
- https://github.com/SeaGL/organization/issues/167  define CoC stuff in terms of what that means for moderation strategies around abuse for the 2021 conf

**Comment by koronkowy** [comment]
Per all hands this week, look for external CoC chairs has ended and it will be turned internal. - @altsalt made note of this in the all hands

Additionally, I have submitted a PR with included some bolstering of the CoC that involves verbiage about how the CoC committee functions in lieu of a formal committee existing.

Any and all eyes on the new CoC updates are beneficial, ty!

https://github.com/SeaGL/organization/pull/179

**Comment by koronkowy** [comment]
In lieu of a proper CoC committee, drafted some updates and they got merged in. Encouraging folks to submit additions or changes at next all hands.

**Comment by koronkowy** [comment]
YAY we met today at 11 am PST

New committee formed: Chair - @rachelkelly, members: @sntxrr @dorian-wood @koronkowy @altsalt
