### ISSUE TITLE
Bye freenode :'(

### ISSUE THREAD

**Issue by nhandler** [SeaGL/organization#125]
Long story short, freenode is under new management. All of the old staff have resigned and most have gone off to start the new https://libera.chat/ . A lot of prominent FOSS projects have already migrated to the new network. We already have #seagl registered on libera.chat. We should make this official. Right now, there is a lot of social media attention on libera.chat. So if we were to announce our move, it would likely get some attention and possibly attract some new folks to join the channel.

Some tasks:
- Update the website
- Share this change out on social media
- There is possibly some Matrix bridge that needs to be updated
- attend.seagl.org will neeed an update

**Comment by funnelfiasco** [comment]
+1 to officially migrating to libera.

**Comment by altsalt** [comment]
I have started the process of bridging in the network/channel to SeattleMatrix's Matrix server. Once that is done, we should have the details updated on the website before doing a social media blast.

**Comment by eximious** [comment]
I think it might be nice to include a link to some documentation since some
of us haven't had to add a new network to IRC tooling in ~10 years or more.
Deb

**Comment by altsalt** [comment]
I finally setup the tombstone, so think we're done here, RIP freenode
