### ISSUE TITLE
select SeaGL 2021 theme

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#130]
## From email entitled, "Year 9 swag idea"
- 9 is 3 squared
- still the year of online, so the Brady Bunch / Hollywood Squares thing fits. SeaGL t-shirt with FLOSS mascots in a grid?
- "if you tell 3 friends and they tell 3 friends"
- IX in roman numerals
- Last single digit in base 10
- Cloud? Nein!
- 9 lives, PR of our mascot with a cat ( SeaGL is the weekend after Halloween, so options with that )
- Why was 6 afraid? Because 7 8 9. ( as seen in some kid joke thing )
- a stitch in time saves nine ( fix it now or fix it many times in the future )
- 9 to 5
- whole 9 yards
- to the nines
- formerly 9 planets of the Solar system
- rubik's cubes?
- tic tac toe

**Comment by rachelkelly** [comment]
Love the following:
> a stitch in time saves nine
> whole nine yards
> to the nines

**Comment by eximious** [comment]
Cloud Nine
Nine Circles of Hell (this one will be tricky)
The Nine, epithet for the Nazgûl in J. R. R. Tolkien's Middle-earth
Revolution No. 9

**Comment by altsalt** [comment]
Personally I am leaning a bit towards:

- to the nines
- a stitch in time saves nine
- whole nine yards
- cloud nine

I like that the first two are very aligned with a fashion show... aka #148

**Comment by altsalt** [comment]
Poll for voting: https://star.vote/yt4kt6x1/

**Comment by koronkowy** [comment]
@altsalt not sure but I think this is already done too
