### ISSUE TITLE
Engage with Linux Foundation events running in Seattle, September 27-October 1

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#131]
https://www.linuxfoundation.org/en/press-release/the-linux-foundation-announces-open-source-summit-embedded-linux-conference-2021-will-move-from-dublin-ireland-to-seattle-washington/

We would like to table this event, but not for the fees they are requesting...

@ChristyWilson perhaps you can reach out and see if we can do some in-kind advertising, as well as on-the-ground support. Also, are you interested in joining me to table it?

@lufthans having the prospectus ready will assist with this.

CFP closes on June 13th, before our next meeting. I'll be submitting something, but what is the best way to let any other SeaGL staff know they can too? (Also, the link to their CFP is currently broken, will need to figure that one out..)

**Comment by altsalt** [comment]
Found the correct links, which have live CFPs
- https://events.linuxfoundation.org/open-source-summit-north-america/
- https://events.linuxfoundation.org/ospocon/
- https://events.linuxfoundation.org/embedded-linux-conference-north-america/
- https://events.linuxfoundation.org/linux-security-summit-north-america/

**Comment by altsalt** [comment]
We had a good phone call last month, I've sent them the prospectus and am waiting to hear back. Sounds like we will have a table with at least two folks.

**Comment by koronkowy** [comment]
@altsalt Please follow up with me on this one as needed.

**Comment by koronkowy** [comment]
I got registered!

Budget should be incoming re: Handbill printing costs per finance/partnerships meeting today: https://github.com/SeaGL/organization/issues/151

**Comment by koronkowy** [comment]
Conferences are over! :)
