### ISSUE TITLE
Finish SeaGL style guide

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#132]
We started one for the graphics team last year, but we should finish it. It will help with the press kit tickets.

**Comment by altsalt** [comment]
The stub of a guide can be found here: https://github.com/SeaGL/seagl.github.io/issues/85

**Comment by altsalt** [comment]
Here's some relevant market research:

## press page/kits
- https://stackconf.eu/about/#press
- https://apache.org/press/
- https://apache.org/press/media.html
- http://www.securitybsides.com/w/page/19532810/Media

## trademark usage
- https://opensource.org/logo-usage-guidelines
- https://opensource.org/trademark-guidelines
- https://apache.org/foundation/marks/
- https://www.linuxfoundation.org/trademark-usage
- https://snowdrift.coop/trademarks
- https://wiki.snowdrift.coop/communications/guidelines

## brand guide
- https://www.washington.edu/brand/

there are two press kit issues (#26 and #27) that are pretty linked to this as well.

**Comment by altsalt** [comment]
Here's another good reference!

https://gitlab.com/snowdrift/design/-/wikis/Design-Guide

**Comment by mateuskrause** [comment]
First draft version [here](https://drive.google.com/file/d/1G5o53IYbVq4RfkGMglH9CKVukqaao_ru/view?usp=sharing). Still just the basics, without images.

**Comment by mateuskrause** [comment]
Just a quick update, here is the [2nd draft](https://drive.google.com/file/d/1Cj66Helu0kXows__SUgcJ0O4KAWntsJ0/view?usp=sharing). I just added some example images and started thinking about how to integrate on the press page.

**Comment by altsalt** [comment]
This seems done enough to close the issue. Reopen if you disagree @mateuskrause
