### ISSUE TITLE
plan geeky fashion show

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#148]

**Comment by eximious** [comment]
Nerdy characters, famous technologists, abstract costumes that represent tools/libraries/reg expressions. 

Fashion show should have a stated age range that we're aiming for. Just to make sure we don't end up mixing and matching in a way that is surprising or confusing to participants.

**Comment by altsalt** [comment]
Suggestions from 2021-10-04:
- themes: masks, mug kilts, con t-shirts, cloud print fashion
- considerations: age appropriate guidelines
- time slot: after event on friday or saturday, friday for mako, saturday maybe for trivia/scavenger hunt
  - maybe before keynotes?
    - more of an icebreaker
    - 5-10 minute parade to build energy

**Comment by koronkowy** [comment]
This happened, woo!
