### ISSUE TITLE
get CFP office hours plan together

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#149]

**Comment by funnelfiasco** [comment]
Dates set:

* Sun Aug 1, 3pm PDT
* Tues Aug 3, 5:30pm PDT
* Sat Aug 7, 3pm PDT

Promotion plan

- [ ]  Announce on Twitter
- [ ]  Announce on Mastodon
- [ ] Create Facebook events
- [ ] Publish blog post
- [ ] Schedule more tweets

**Comment by funnelfiasco** [comment]
Blog post drafted in [seagl,github.io#256](https://github.com/SeaGL/seagl.github.io/pull/256). I'm considering it a blocker for the Facebook events.

**Comment by funnelfiasco** [comment]
Okay, blog is live and messages are sent. I have tweets scheduled at the start of each session and I should be around to post toots at those times as well. I'll also promote it some more in the ad hoc t{wee,oo}ting I do during the week.

**Comment by altsalt** [comment]
Here is the message I've been posting around IRC/Matrix:
> I realize that I'm a month late in advertising this around the irseas. The SeaGL (virtual, November 5/6) CFP is open for another week (maybe a bit beyond)! We've got two upcoming office hours for tightening up proposals. All FLO related talks welcomed, not just Linux stuff, and we love new speakers/not-the-norm conference presentations. More info (and links) can be found in this post: https://seagl.org/news/2021/07/30/office_hours.html

**Comment by altsalt** [comment]
Thanks for making this happen!
