### ISSUE TITLE
name SeaGL colors via community poll

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#154]
In today's meeting, we discussed having the community submit and vote on names for the colors in the [style guide](https://github.com/SeaGL/organization/issues/132). @altsalt volunteered to set up a form for name submission

**Comment by altsalt** [comment]
@mateuskrause could I get an image of each color with the updated RGB, but still no names beyond generic ones for making the poll? Plan is to put up a form where folks can submit suggestions for each color, then when we have enough for one of the colors, we'll run a star.vote between its options for a couple of weeks till we have names for all.

**Comment by mateuskrause** [comment]
@altsalt can be something like this? The individual images are [here](https://drive.google.com/drive/folders/1dgohkPiFb9AEHV877wWaNm4FnF5wyR37?usp=sharing). I can change the shape and the infos if needed. 
![colors overview](https://user-images.githubusercontent.com/47651648/130079451-273e51cf-46a4-42df-b06a-1a25f90d045a.png)

**Comment by altsalt** [comment]
Yeah, this is perfect. Don't think higher resolution is necessarily better. Thanks!

**Comment by altsalt** [comment]
How does this look?

https://docs.google.com/forms/d/e/1FAIpQLSdIIXHJPVRy_r3O9R5aXHUJKwvVl7nmmQ_ZYzyaJ5ER4UcNng/viewform?usp=sf_link

**Comment by funnelfiasco** [comment]
I think it looks good.

**Comment by altsalt** [comment]
Alright, lets get this into the various social postings.

**Comment by altsalt** [comment]
Shortened link as well: https://forms.gle/6qSQHC2HodwhDbTQ7

**Comment by mateuskrause** [comment]
@altsalt the images of each color by itself are exported. As the meeting notes say to export with RGB text and I think it was supposed to be HEX, I exported multiple versions. All links to Google Drive:

- [images with the hex color text](https://drive.google.com/drive/folders/1kk7IsVIigsm9l4qqiUCGXq2wtZSbl0pK?usp=sharing)
- [images with the rgb color text](https://drive.google.com/drive/folders/19XN1VLz-y-lIa2EaQD57cE52AlWzg9BR?usp=sharing)
- [images with the rgb+hex color text](https://drive.google.com/drive/folders/10j7CgEekm8LDPKajAMWivfGrMvvjCNFv?usp=sharing)

**Comment by koronkowy** [comment]
I think this is all wrapped up. Did we do a final social media / blog post or something re: the results at all?

**Comment by mateuskrause** [comment]
Just need to update the style guide with the color names, and I think is a good idea to share, at least in social media.

**Comment by altsalt** [comment]
Tidal Blue
Puget Sound
Deep Ocean
French Fry Gold
Wet Sand
Brave Gull
Gloomy Sky
Stormy Sky
Storm Cloud
Penguin Black
Bread For Screaming At
Eggshell

19 votes, tallied using the STAR method.

**Comment by funnelfiasco** [comment]
Since have names, I'm going to close this issue and open additional issues for the post-work.
