### ISSUE TITLE
Update Repo Labels / Readme to Reflect All Committees

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/organization#155]
It looks like the readme for this repo has a different number of committees and some committees missing. This is maybe part of an overall org chart formalization / documentation update.

Additionally, labels don't exist for all committees so it's hard to assign/tag/etc. committees that don't have a label. At least, for me, having one for volunteer committee stuff is important and valuable so I can be notified of issues. I am not quite sure how to spin these up.

**Comment by altsalt** [comment]
Related to #78 and #79

**Comment by koronkowy** [comment]
Updated repo names, and readme of committees: https://github.com/SeaGL/organization/pull/179 with this pull request

Labels are not updated tho....

**Comment by altsalt** [comment]
Labels have been updated in this repo, as well as having defaults for new repos set at the GH organizational level. I haven't gone through and done color matching, but most descriptions have been updated.

**Comment by altsalt** [comment]
Oh, Teams have also been created for each committee at the GH organizational level. They aren't really in use, but I figure they can be pinged directly with things like @SeaGL/volunteers and probably have other functionality which should be considered.
