### ISSUE TITLE
Create 2021 social media banner

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#156]
We should have a banner that includes the SeaGL 2021 dates and any relevant information, perhaps a URL, keynotes, etc. @funnelfiasco and @mateuskrause it looks like there was one created for Twitter but I can't find it in any of the files. We should probably have a document of things like this which need to be created each year, alongside the various dimensions for the different social media sites.

**Comment by mateuskrause** [comment]
In today's outreach meeting, we discussed about having all the files on the outreach folder in this repo, so anyone can download and edit

**Comment by mateuskrause** [comment]
@funnelfiasco one thing I forgot to mention at the outreach meeting yesterday is to update the Twitter and Mastodon banners with the new ones. We have two versions, with and without the conference date. The last one is for use after the event. The files are in the comment above.

**Comment by funnelfiasco** [comment]
> update the Twitter and Mastodon banners with the new ones.

Done! I'll change them to use the un-dated ones on Sunday or Monday.

**Comment by altsalt** [comment]
The YouTube banner is still out of date too...

**Comment by funnelfiasco** [comment]
> The YouTube banner is still out of date too...

I don't seem to have access to our channel under either bcotton@{funnelfiasco.com,seagl.org}

**Comment by altsalt** [comment]
You now have access on both. When you goto youtube, you need to click in the top right and switch accounts to the seagl one I think.

**Comment by sntxrr** [comment]
I just attempted to update the Youtube "banner" - and it honestly looks horrible.  :(

Youtube seems to want me to upload an image that is at least: 1024 x 576 - for some reason, [this](https://github.com/SeaGL/organization/blob/main/promotion_outreach/design/social-media/profile-banner/seagl2021_profile_banner_with_date.png) isn't showing up with its correct size.. :(

**Comment by mateuskrause** [comment]
@sntxrr There is a different banner just for youtube, [this one](https://drive.google.com/file/d/1yigzD5AjoygrhuT2wXIILClax_tcTr4t/view?usp=sharing).
The size is different because the banner can be viewed on mobile, desktop, tvs, etc and is cut to the appropriate size.

**Comment by sntxrr** [comment]
Thank you @mateuskrause - updated!

**Comment by funnelfiasco** [comment]
Un-dated banners added to social accounts! I'm goin got go ahead and close this because I don't think there's anything else needed here.

**Comment by altsalt** [comment]
I do wonder whether we want to create/use a banner with the 2022 dates... Thoughts?

**Comment by funnelfiasco** [comment]
I thought about that. We certainly could, although the current banners are based on the "cloud nine" theme, so it'd be nice to have a new theme nailed down.

**Comment by altsalt** [comment]
Let's talk about it at the next outreach meeting. No need to make any changes till then. Thanks so much for flipping them to date-less so quickly!
