### ISSUE TITLE
Blog on home page + groups announcement of partnership prospectus etc for 2021

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/organization#162]
A blog post on the home page + a post on the https://groups.google.com/g/seagl_organize group would be helpful to announce / make the prospectus easier to find now that it is public. I'd love to have somewhere easier to direct folks.

**Comment by funnelfiasco** [comment]
@koronkowy do you want to write that post or are you making a request for it?

**Comment by koronkowy** [comment]
I think it would be a valuable post, if not on the home page at least in group.

**Comment by koronkowy** [comment]
Hans has got this on the radar now post partnership meeting! WOO

**Comment by altsalt** [comment]
@lufthans making sure you're pinged on this

**Comment by koronkowy** [comment]
It's too late to really advertise sponsorship on the blog this year, I think. Maybe next year.
