### ISSUE TITLE
Uniforming Sizing for Sponsor/Partnership Logos 2021

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/organization#166]
Currently the logos for sponsors sizing / formatting are inconsistent, some very large and unreadible.

<img width="1478" alt="Screen Shot 2021-09-13 at 5 21 15 PM" src="https://user-images.githubusercontent.com/43873379/133173741-9a7e3e67-24e4-481c-af49-9c98086abafc.png">

**Comment by AndrewKvalheim** [comment]
Thanks, tracking at SeaGL/seagl.github.io#270
