### ISSUE TITLE
Budget request: Social sticker pack design

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#170]
The Promotion & Outreach Committee would like to commission the design of SeaGL "stickers" for Telegram/Signal/etc. We estimate this would cost about $200.

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by lufthans** [comment]
Approved and thank you, we're looking forward to them

**Comment by funnelfiasco** [comment]
Hi folks, any update on this reimbursement request?

**Comment by NormanGross** [comment]
Moved receipts to 2022 reimbursement.

@funnelfiasco if you have access, need preferred payment method (ACH, PayPal, Wire Transfer, Wise, or Check) and address on the spreadsheet located at:  
https://docs.google.com/spreadsheets/d/1hOt6YITIfgqHzrJhDTdGkzzQQqWBWja_eDuwgna-_4E/edit?usp=sharing

If you do not have access, please drop the info in a text file at:
https://drive.google.com/drive/folders/1EsANusQ8u4SyuxEr7pCcFuYSNAzSj5LD?usp=sharing

**Comment by funnelfiasco** [comment]
@NormanGross I don't have access to the spreadsheet or to the drive folder listed as an alternative plan. I requested access to the spreadsheet and will add the information once that's granted.

**Comment by NormanGross** [comment]
Ok.  @lufthans is working on another option/form to allow people to supply this sort of info.

**Comment by NormanGross** [comment]
Nevermind @funnelfiasco .  The other option may be a bit.   So I did give you edit rights to the form.   Holler if you have any issues/questions.

**Comment by NormanGross** [comment]
Sent to OSI for processing.

**Comment by NormanGross** [comment]
Per OSI payment set.  Ben, can you please verify.

**Comment by funnelfiasco** [comment]
Received, thanks! (Sorry about the late reply)
