### ISSUE TITLE
Interstitials for 2021 (inbetween talks slide/animation thingies)

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/organization#174]
Development for interstitials, the things rolled in between talks that have information needs to happen at some point.

I have semi-volunteered because I have done these before but someone will have to get to me with the kinds of things we want on interstitials this year.

Some pain points that could be alleviated is having one that's the same or a couple that are the same showing schedule, sponsors maybe, volunteer requests, etc. vs full on each transition customizing them for the next talk. Unless we could do something over-lay'y (seen similar at ShellCon I think) to announce the next upcoming.

If anyone has the previous year's ones that would be great but we might not have them recorded anywhere. Do they live on a file or can we reach out to whoever did them last year?

Things to think about at least and not forget.

**Comment by koronkowy** [comment]
@sntxrr MAY have them or at least be able to recount them.

Anyone else?

**Comment by koronkowy** [comment]
I think that the ad roll / interstitials are on their way / in development with @mateuskrause

**Comment by mateuskrause** [comment]
For last year I did one image with a "blank space", and I don't remember what exacly was done to add the infos. @funnelfiasco do you know something about this?
I can help on this.

**Comment by eximious** [comment]
Hi, 
I'd like to make sure we get all the social events listed on a slide. 
All the social events are described here, https://seagl.org/news/2021/10/28/seagl-2021-social.html

1. Monica is going to be adding a link for the Costume contest audience voting. 
2. Rachel is going to bring in a link for the DevOps games on Friday night. 
3. Don & the tech team are going to provide a link for the "social track" which is what we should be directing people to for all other social events including; Cocktails/Mocktails with Mako on Friday night, Costume contest winners announced and TeaGL on Saturday day time, and Sandwich hour and the Trivia on Saturday night.

**Comment by funnelfiasco** [comment]
> For last year I did one image with a "blank space", and I don't remember what exacly was done to add the infos. @funnelfiasco do you know something about this?

I don't, sorry. I wasn't involved in this task last year.

**Comment by altsalt** [comment]
A list of content is here:
https://pad.seattlematrix.org/p/SeaGL_2021_interstitial_listings

**Comment by mateuskrause** [comment]
I finished the template and started to create the actual images, all files [here](https://drive.google.com/drive/folders/1gvvYejByse8ys9Dw52gebF-CxbhGZOpW?usp=sharing). (Still work in progress)

Beyond the sponsors and social events, there are any other case needed?

**Comment by altsalt** [comment]
These look amazing, thanks @mateuskrause ! Other than those, something for the CoC link, Feedback link, Stickers link, and Attend link.

**Comment by mateuskrause** [comment]
@altsalt do you mean a specific interstitial for the coc, feedback, stickers and attend? It would be nice

**Comment by altsalt** [comment]
Yes please! May be more than one if they don't fit.

**Comment by mateuskrause** [comment]
maybe on the slideshow they can appear for a shorter time and we can use one per slide.

**Comment by mateuskrause** [comment]
finished and on [google drive](https://drive.google.com/drive/folders/1gvvYejByse8ys9Dw52gebF-CxbhGZOpW)!

**Comment by koronkowy** [comment]
Interstitials happened, woo!
