### ISSUE TITLE
Setup a #SeaGL-volunteers:seattlematrix.org channel

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/organization#175]
This will be used to help direct volunteers day of into a central location.
Can be private for now before we determine the best use case.

this being defined so when meet.seagl.org pages flavored for volunteers (ex. seagl.org/meet/volunteer) is created OR emails sent to volunteers or FAQS will information about where volunteers need to head to in the matrix and how to get into matrix period.

**Comment by altsalt** [comment]
Done `#SeaGL-volunteers:seattlematrix.org` [also volunteer and volunteer(s):matrix.org]
