### ISSUE TITLE
Review amendments to CoC

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/organization#180]
Please check out some bolstering of the CoC I included in this PR:
https://github.com/SeaGL/organization/pull/179

Before this goes live on the site, if it does, I want to get feedback by any interested parties.

**Comment by koronkowy** [comment]
If CoC does change, we need to announce such to the community and also update it on the website.

**Comment by funnelfiasco** [comment]
I love the updates to the CoC. It seems to be a clear expression of our values and how we will interpret and enforce them. The only thing I would change is having it be a separate PR so it's easier to manage if there's feedback on the other changes there. :-)

**Comment by koronkowy** [comment]
> I love the updates to the CoC. It seems to be a clear expression of our values and how we will interpret and enforce them. The only thing I would change is having it be a separate PR so it's easier to manage if there's feedback on the other changes there. :-)

Hehe, I realized this immediately after. Apologies.

**Comment by dorian-wood** [comment]
Did a minor edit to improve the flow of the opening paragraph.
https://github.com/SeaGL/organization/pull/186

**Comment by koronkowy** [comment]
Accepted improvements! I think the CoC is fully baked now and needs to make it to the site + a blog (simple announcement) and social media heads up.

**Comment by koronkowy** [comment]
Blog posted and all, woo!
