### ISSUE TITLE
Table at OSS

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#182]
- [x] get conference tabling gear from storage before OSS (Salt)
- [x] design handbill four-to-a-page handouts for OSS (Outreach)
- [x] print handbill four-to-a-page handouts for OSS (Salt)

**Comment by koronkowy** [comment]
Relevant issue: https://github.com/SeaGL/organization/issues/171 - handbills

**Comment by altsalt** [comment]
Here is the group chat on Matrix: https://matrix.to/#/!jVmnsAQkNkbIrHXnfQ:matrix.org?via=matrix.org&via=gnome.org&via=seattlematrix.org

**Comment by koronkowy** [comment]
Is everything squared away post-tabling? @altsalt

**Comment by altsalt** [comment]
I do believe so, thanks for being there everyone. Successful event I'd say!
