### ISSUE TITLE
speaker digital gift brainstorming

### ISSUE THREAD

**Issue by lufthans** [SeaGL/organization#188]
What are some ideas for digital speaker gifts this year?

This is our 9th year.

The unannounced theme is "on cloud nine", but we can take that to a "your cloud" or "private cloud" direction

Gift don't need to match the theme, it's just a prompt.

**Comment by lufthans** [comment]
Graphical notes or avatar caricatures

**Comment by lufthans** [comment]
fungible tokens like a "SeaGL speaker" badge that can be used over and over again

**Comment by lufthans** [comment]
speaker-specific digital sticker pack

**Comment by altsalt** [comment]
Dunno why, but a gift of a VPS or VPN just came to me... but I think we'd only be able to budget one month.

**Comment by altsalt** [comment]
Taken care of for 2021, we may need to re-up for 2022 but closing this issue for now.
