### ISSUE TITLE
Social media images for social events

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#204]
@mateuskrause if you have time, can you please make some quick images for the social events? I see two approaches, please do whichever works best for you.

1. A general "social events" image that we can use for all of them (except TeaGL, which you already did)
2. An image for each of the events in SeaGL/seagl.github.io#293

I'd like to start promoting these as soon as the social post goes live tomorrow, which is why a generic image is fine. Sorry for the short notice!

**Comment by funnelfiasco** [comment]
@mateuskrause one issue I just noticed. For the cocktails and mocktails, it's Mak**o**, not Maki

The rest look great

**Comment by mateuskrause** [comment]
@funnelfiasco I uploaded the corrected version, [here](https://drive.google.com/drive/folders/1njlK8OrAml7jJ8XDFjaAlYlpwG7rXEiV?usp=sharing).

**Comment by koronkowy** [comment]
This got wrapped up, woo!
