### ISSUE TITLE
2023 Sticker pack update

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#220]
This will be where we work on additional stickers for 2022.

**Comment by funnelfiasco** [comment]
* Patch clapping

**Comment by AndrewKvalheim** [comment]
Brainstorming:

- Drinking coffee
- Drinking tea
- Eating sushi
- Stealing a fry
- Having a fry stolen
- Angrily screaming at bread
- Happily screaming for attention
- Soaring through clouds
- Standing in the rain
- Flying through a thunder storm
- Flying at night with the moon
- Flying among fireworks
- Flock flying into the sunset
- Flock circling/pestering a fisherman
- Colony on a rocky island
- Relaxing in the sun
- Enjoying a bonfire
- Sleeping in a nest
- Diving underwater
- Riding choppy waves
- Friends with another gull
- Giving you a flower
- Giving a gift to an otter
- High-fiving an octopus
- Seagull chick hatching
- Nest of chicks begging for food
- Using a wing to shelter a small creature
- Building a sandcastle
- Hoarding sand dollar treasure
- Wearing headphones made of clamshells
- Riding a bicycle
- Flying with a rocket strapped to their back
- Delivering a letter
- Hauling an unreasonable amount of cargo
- Floating upside-down with a scuba helmet
- Tangled in seaweed
- Pinched by a crab
- Buried in the sand as the tide rises
- Lounging in an inner tube as a shark fin approaches
- Surrounded by circling sharks
- Firefighter
- Doing a science experiment
- Cowboy coding
- Yak shaving
- Dogfooding
- Painting a bike shed
- Talking to a rubber duck
- Reading the manual
- Uncovering bugs
- Standing atop a tower of turtles
- Juggling fish
- Airlifting a whale
- Kicking a computer into the sea
- Biting through a network cable
- Speaking at a podium

**Comment by AlfredoMS** [comment]
Now open for 2023 as well

**Comment by AlfredoMS** [comment]
Doing a poll soon to decide the 10 best to order for 2023. The poll will happen before August end, link will be send on Matrix.

**Comment by AlfredoMS** [comment]
Vote here, top 10 will be send to the designer: https://star.vote/n1ym16ze/

**Comment by AlfredoMS** [comment]
done
