### ISSUE TITLE
Replace failed-stream for lightning talks with raw videos

### ISSUE THREAD

**Issue by wolftune** [SeaGL/organization#224]
https://archive.org/details/SeaGL2021-Lightning_Talks is a recording of the failed stream

Since the videos were pre-recorded anyway, the stream video should be removed and the separate pre-recorded videos should be posted.

**Comment by AndrewKvalheim** [comment]
@sntxrr Can you please add the pre-recorded lighting talks to Nextcloud?

**Comment by altsalt** [comment]
Checking in on whether this was accomplished?

**Comment by wolftune** [comment]
The archive.org link still shows the failed stream version, and that should probably just be removed and the pre-recorded files (ideally separately as just a playlist) would be uploaded to that item instead.

**Comment by AndrewKvalheim** [comment]
I can get the videos uploaded and linked, just need a copy of them.

**Comment by altsalt** [comment]
@sntxrr as I recall you had the source videos, right?

**Comment by wolftune** [comment]
I kept a copy of my own at least in case that's helpful.

**Comment by sntxrr** [comment]
I do have the raw streams from Streamyard, yes. I need to retrieve them from Glacier before I can do anything else with them.

**Comment by sntxrr** [comment]
I've now shared the video with @AndrewKvalheim and he'll do the things he did before

**Comment by AndrewKvalheim** [comment]
I’m just seeing the same stream recording with frozen video in both talks.

**Comment by AndrewKvalheim** [comment]
Got a copy of the original videos and replaced the failed recordings. Thank you @wolftune, and sorry it took so long!
