### ISSUE TITLE
2020 speaker gifts reimbursement

### ISSUE THREAD

**Issue by lufthans** [SeaGL/organization#225]
Purchase of plush Seagulls for speaker gifts from Animal Den: $310.80

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by lufthans** [comment]
https://drive.google.com/drive/folders/1tRxAP_GIfnIERIfn1e3pI4IkZu3bmmF_

**Comment by NormanGross** [comment]
Cannot access receipt.

**Comment by NormanGross** [comment]
New Link.  Hope if works.

https://drive.google.com/file/d/1mLgFteMiTgAnb7jJwGz_eKXXrvppLSRh/view?usp=sharing

**Comment by NormanGross** [comment]
Moved receipt to 2022 finance area.   Need to see if more info is needed.

**Comment by NormanGross** [comment]
@lufthans Did you want to add your perdiem for 2022 to this?

**Comment by NormanGross** [comment]
Sent to OSI for processing.
