### ISSUE TITLE
2021 Speaker gift reimbursement

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#235]
The [receipt for the speaker gifts](https://drive.google.com/file/d/1YmvirFuQgX-CU6fUH6hBkTwMFJSGUSDh/view?usp=sharing) is in Google Drive.

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by funnelfiasco** [comment]
Hi folks, any update on this reimbursement request?

**Comment by altsalt** [comment]
@lufthans @NormanGross I know we are waiting on OSI to get back to us, but this does need to get taken care of sooner than later and want to make sure it is still on radars.

**Comment by NormanGross** [comment]
Moved receipt to 2022 reimbursement.

@funnelfiasco if you have access, need preferred payment method (ACH, PayPal, Wire Transfer, Wise, or Check) and address on the spreadsheet located at:  
https://docs.google.com/spreadsheets/d/1hOt6YITIfgqHzrJhDTdGkzzQQqWBWja_eDuwgna-_4E/edit?usp=sharing

If you do not have access, please drop the info in a text file at:
https://drive.google.com/drive/folders/1EsANusQ8u4SyuxEr7pCcFuYSNAzSj5LD?usp=sharing

**Comment by NormanGross** [comment]
Sent to OSI for processing.

**Comment by funnelfiasco** [comment]
Received, thanks (sorry for the delayed response)
