### ISSUE TITLE
IRC-bridged Matrix rooms kick idle members

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#237]
The Libera.​Chat IRC bridge automatically [kicks idle members](https://github.com/matrix-org/matrix-appservice-irc/issues/1268) out of our Matrix rooms. SeaGL is particularly affected due to our seasonal usage pattern.

Possible solutions:

- Change the behavior of the public Libera.​Chat bridge
- Run our own bridge without this behavior
- Un-bridge all of our rooms except for a dedicated bridged room

**Comment by AndrewKvalheim** [comment]
> @AndrewKvalheim changed the title ~~**IRC-bri**~~ **IRC-bridged Matrix rooms kick idle members**

Sorry, my <kbd>Enter</kbd> key is where <kbd>D</kbd> used to be.

**Comment by altsalt** [comment]
Going through restricted / staff channels that are bridged and decoupling them.

Still need to decide on solution for public facing ones.

**Comment by AndrewKvalheim** [comment]
For now we’re trying this option:

> - Un-bridge all of our rooms except for a dedicated bridged room

The dedicated room is [`#irc:seagl.org`](https://matrix.to/#/#irc:seagl.org).

**Comment by AndrewKvalheim** [comment]
The affected bridge [no longer exists](https://github.com/SeaGL/organization/issues/397).
