### ISSUE TITLE
AWS bill for Nextcloud is high

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#238]
Do we need the 1 TB of EBS? Can it use S3 instead?

**Comment by AndrewKvalheim** [comment]
We think it should already be using S3 for data storage. @strugee will look into shrinking the EBS volume.

**Comment by strugee** [comment]
Volume shrunk to 20GB! I didn't delete the old one yet just in case. Can someone poke around at the instance and make sure everything looks ok, just to be sure? I don't have an account.

**Comment by AndrewKvalheim** [comment]
Looks good. Thanks!

**Comment by strugee** [comment]
Just destroyed the live EBS volume. Originally I was going to keep the snapshot I took just in case, but it seems like it was also going to be billed at a reasonably high rate so I killed that too.
