### ISSUE TITLE
Subtle logo revisions

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#24]
While preparing last year's badge I noticed a few graphical errors in the logo that make it difficult to work with—e.g. horizontal asymmetry of the ribbon makes centering nontrivial, vertical asymmetry makes alignment with page design elements impossible, etc.—and in correcting those I was lured into thinking about other adjustments as well.

I'd like to propose a few revisions to the logo that should be subtle enough to not feel like a redesign.

| Current | Variant A |
|-|-|
| <img src="https://user-images.githubusercontent.com/1844746/76157054-ab281080-60b8-11ea-9cb3-2b142494dc0a.png" alt="SeaGL logo - 2013 design" width="256"> | <img src="https://user-images.githubusercontent.com/1844746/76157032-47054c80-60b8-11ea-9cbe-37972f037a30.png" alt="SeaGL logo - Variant A" width="256"> |

### Changes

- Expected results:
    - The seagull is more emphasized.
    - Graphical elements are cleaner and more balanced.
    - The logo fits better in a square bound.
    - The seagull's face looks less human.
- Edits:
    - Decrease the size of the ribbon.
    - Increase the size of the seagull.
    - Reshape the seagull's head and beak.
    - Add a red spot on the seagull's beak.
    - Reshape the horizon from an oval segment to an arc.
    - Decrease the range of text weights.
    - Match line thicknesses to text weights.
    - Decrease the length of the ribbon's folds.
    - Decrease the depth of the ribbon's end cuts.
    - Correct the asymmetry of the ribbon.
    - Remove the discontinuity at the edge of the background.
    - Remove the white drop shadow from the text.
    - Align the highlight on the seagull's tail.
    - Fine-tune the shape of the seagull's body.
    - Round near-gray colors to pure gray colors.
- Bonus:
    - The logo was made with free software. ([see also](https://github.com/SeaGL/seagl.github.io/blob/2dfdca1/img/logo.svg?short_path=16813ee#L2))

Thoughts? Good idea / bad idea? Other changes you'd want to see while we're at it?

**Comment by altsalt** [comment]
Looks great to me! On the note of the, "Add a red spot on the seagull's beak," there was some discussion about reducing our color pallet. However, while we are sticking with all of them, these all seem like excellent improvements! Thank so much!

**Comment by eximious** [comment]
Amazing! Thanks so much for doing this. I'm totally into a more seagull-y
looking seagull.
Deb

**Comment by AndrewKvalheim** [comment]
Updated `SeaGL/Logos` and the website.
