### ISSUE TITLE
Shutting down EC2 instances breaks DNS

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#240]
Unless you use an elastic IP, IP addresses in EC2 are ephemeral and are lost when the instance is shut down. Because of this behavior, our DNS records are fragile and need to be updated whenever we shut down and start instances (reboots are OK). `nextcloud.seagl` at least is affected by this, and probably others.

The solution is probably to use A alias records, which is Route 53 magic.

**Comment by altsalt** [comment]
Status on this @strugee ?

**Comment by AndrewKvalheim** [comment]
I reserved an Elastic IP, updated `A dokku.seagl.org`, and CNAMEd `osem` to `dokku`.
