### ISSUE TITLE
seagl.org does not redirect to HTTPS

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#243]
Unclear on if this is a regression or not. CC @sntxrr, do you know if there's any reason _not_ to do this?

**Comment by AndrewKvalheim** [comment]
[This](https://github.com/SeaGL/seagl.github.io/settings/pages) used to be checked; no idea why it’s not anymore:

> <img src="https://user-images.githubusercontent.com/1844746/158249499-85726397-7f5e-4dd1-b977-07ba39846511.png" alt="Enforce HTTPS" width="648" />

If it were just up to me I’d say set HSTS including subdomains and let any problems that causes be other problems. :)

**Comment by strugee** [comment]
Yep, sounds good to me.

**Comment by strugee** [comment]
Looks like I don't have permission to enable this though

**Comment by AndrewKvalheim** [comment]
Thanks, I’ve checked it and sent you an invitation for the permission. We should look into what might cause GitHub Pages to automatically disable that and discuss HSTS with @sntxrr.

**Comment by AndrewKvalheim** [comment]
Happened again. Can we get GitHub Pages to send HSTS? https://github.com/isaacs/github/issues/1249

**Comment by altsalt** [comment]
Pinging @strugee and @sntxrr on this, let's make sure it is covered sooner than later.

**Comment by altsalt** [comment]
Any updates on this?

**Comment by strugee** [comment]
IIRC we talked to GitHub Support about this and they helped us fix the DNS check that was causing HTTPS to turn off all the time. However I still don't see HSTS headers despite "Enforce HTTPS" being checked in Pages settings. So we probably need to ask support again. (I unchecked and rechecked the checkbox, though I didn't wait before trying again.)

**Comment by AndrewKvalheim** [comment]
“Enforce” probably means just to redirect from HTTP. I think it would be generally inappropriate for GitHub Pages to set HSTS without giving the user a stern warning first.

**Comment by AndrewKvalheim** [comment]
Related: [orgs/community#4444](https://github.com/orgs/community/discussions/4444)

**Comment by strugee** [comment]
Oh yep, I got confused because new users do indeed get HSTS. Not sure this is worth leaving open.

**Comment by AndrewKvalheim** [comment]
Yeah since HSTS looks like a pain so long as we’re on GitHub Pages let’s forget about that for now. The reported issue hasn’t happened again since contacting support and I’m personally monitoring it now until we get #366 in place.
