### ISSUE TITLE
Select SeaGL 2022 Theme

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#246]
Please add your suggestions!

This is year 10. Lots of potentials to work with: binary, double digits, etc.

**Comment by altsalt** [comment]
from 3/22 meeting:
- Hang ten!
- Ten SeaGLs strumming
- 10, 9, 8... ...blast off!
- The Legend of the Ten Strings (guitar)

**Comment by altsalt** [comment]
More suggestions that have come in:
- “ten-four, roger that, good buddy!”
- ten essentials
- tendons: holding it together

**Comment by strugee** [comment]
This needs a lot of workshopping but maybe something like "say yes to free software" to play off a binary boolean?

**Comment by strugee** [comment]
From https://pad.seattlematrix.org/p/SeaGL_2022_theme_brainstorming:

* 10 finger and 10 toes
* 10 types of people in the world
* X
* this one almost goes to 11
* decadance

**Comment by altsalt** [comment]
Vote here by 9/19: https://star.vote/seagl2022theme/
