### ISSUE TITLE
"Save the Date" material

### ISSUE THREAD

**Issue by mateuskrause** [SeaGL/organization#248]
As requested in the last All-Hands, would be good to have a "save the date" graphic to use in other conferences' slides.

**Comment by mateuskrause** [comment]
@altsalt is there any specification for this? or could we just use a "generic" image size?

**Comment by altsalt** [comment]
No specifications. I'd say having something that can work in a 16:9 and 4:3 slide, also something that can be printed four to a sheet on 8.5x11 paper.

**Comment by altsalt** [comment]
SCaLE will be held July 28-31, 2022 and we have an offer of putting some materials at @g33kdad 's booth. Let's make sure to have a "Save the Date" with any details ready by then.

**Comment by altsalt** [comment]
@mateuskrause pinging about this as we're just over a week out and need time for printing. If you aren't going to be able to put something together, lmk and I'll just update an old asset. Thanks!

**Comment by mateuskrause** [comment]
Sorry for the late answer, @altsalt. I imagine it will be something similar to last year's [handbill](https://github.com/SeaGL/organization/blob/main/promotion_outreach/design/flyers/2021/export/seagl_2021_handbill_print_A.pdf), is it right?
In this case, I can finish something similar. As for printing, is it good to have the complete files by july 25?

**Comment by altsalt** [comment]
Hi @mateuskrause something like that is fine, it'll be four to a sheet. I know we aren't ready to announce keynotes and the most important thing right now is our CFP info which can be found here, https://seagl.org/news/2022/07/06/CFP-Live.html

Hope that helps a bit. Sorry for the delayed response, I've been out of town.

**Comment by mateuskrause** [comment]
I think we can reuse the design from last year in this case. Apart from updating the dates, is just update the text. What do you think about:

> We’re an annual community-focused free/libre/open source software, hardware, and culture event in Seattle, and since 2020, virtually all over the world! Join us for free, no registration required!
Do you have something to share? We are more than excited to invite you to speak! This is a friendly place to people traditionally underrepresented in tech, with uncommonly perspectives, as well as first-time speakers.  The CfP is open through 3 August!

[example with changed text](https://drive.google.com/file/d/1NX_ysFzKqFf0iP-zNFk6Eb-bX1ILYVCF/view?usp=sharing)

About the page size, what format is it? Depending of the size, I have to change the document.
(Print lines will be necessary? Can I group four of these in a sheet and export pdf if so?)

**Comment by altsalt** [comment]
1. Let's make sure to mention this is the tenth year. Probably fine to not have the term "Save The Date" and use the model from last year.
2. If keeping "Save The Date" then move "Seattle GNU/Linux Conference" up or somehow separate it.
3. Pages will be 8.5"x11" and print lines are probably not necessary as I'm guessing this will be hand cut. Grouping four to a page does make sense.
4. If you look at last year's version, a few words were highlighted with color, that's probably a good thing to repeat.
5. Here's some updated text for the second paragraph:
> Do you have something to share? We are more than excited to invite you to speak! SeaGL is a friendly space for first-time speakers, uncommon perspectives, and people traditionally underrepresented in tech.
> 
> The CfP is open now through August 3rd!

**Comment by mateuskrause** [comment]
Update:
![image](https://user-images.githubusercontent.com/47651648/181134857-a8441ff1-9e5a-4b78-9778-bf1060b2180b.png)

One more thing: we can have a version without the blue bars. What do you think?

**Comment by altsalt** [comment]
I don't think the blue bars add much for handbills. Can you add the blue lettering to the first paragraph too? Otherwise LGTM! I'm on the jitsi room btw if you are available.

**Comment by mateuskrause** [comment]
Highlights in the first paragraph, removed date from CfP call.
![image](https://user-images.githubusercontent.com/47651648/181140753-6e141ad8-199e-453b-9507-b3adab58dab1.png)

**Comment by altsalt** [comment]
"CfP is now open!"

**Comment by mateuskrause** [comment]
[single page](https://drive.google.com/file/d/1L8Gvz_2lRO2q-n7RnuJHapiLbX2LLCzw/view?usp=sharing)
[sheet with four](https://drive.google.com/file/d/1vgMlGE55Z4-1ZqW1YIjDyu2iS9IKwk3y/view?usp=sharing)

Ok I think now we're good to go. Something else to change? I'm wondering if there's a chance the sheets are only cut in four, not removing the margins. Would it be interesting to put a cut indicator in this case? (maybe we can just send the single page version)

**Comment by altsalt** [comment]
Looks great, thanks @mateuskrause !

Let's see if @g33kdad can get them printed and cut or whether we should see about shipping them direct to SCaLE...

**Comment by g33kdad** [comment]
I can look for a FedEx Office or similar whilst I'm out and about today.

**Comment by g33kdad** [comment]
@altsalt if you are willing to send the print job off to FedEx Office, the closest one to both my Airbnb and to SCaLE is:
FedEx Office Print and Ship Center - LAX Marriott
5855 W Century Blvd
Los Angeles, CA 90045

**Comment by altsalt** [comment]
Whoops, just saw this, sorry. I'll send it over now.

**Comment by altsalt** [comment]
@g33kdad order sent, cc'ed you on email, couldn't pay because they are a specialty location that doesn't work with the web interface. If you can float it and get reimbursed, that would be best. If not, see if they can take payment over the phone. Thanks and have a great time!

**Comment by altsalt** [comment]
Closing this as the print seemed to work and handbills available at SCaLE
