### ISSUE TITLE
Create reimbursement request issue template

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#261]
Hans or Norm will know what's needed here

**Comment by altsalt** [comment]
This is just one of a variety of templates we might want to consider.

Some official documentation that may be relevant:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file

**Comment by strugee** [comment]
e33832ad6363bcfb149aab3e707b77cf02249697
