### ISSUE TITLE
Do something with inbound DMARC reports

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#265]

**Comment by AndrewKvalheim** [comment]
Some options:

- [parsedmarc-dockerized](https://github.com/dragoangel/parsedmarc-dockerized)
- [Open DMARC Analyzer](https://github.com/userjack6880/Open-DMARC-Analyzer)
- [Fraudmarc Community Edition](https://github.com/Fraudmarc/fraudmarc-ce)

**Comment by AndrewKvalheim** [comment]
I ended up scripting a [minimal notifier](https://github.com/AndrewKvalheim/dmarc-report-notifier) for my own use. Could be appropriate for SeaGL on perhaps a weekly schedule.

**Comment by AndrewKvalheim** [comment]
We’re now monitoring this via SeaGL/seagl-ansible#25.
