### ISSUE TITLE
Review OSEM admin configuration

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#273]
OSEM currently has both `organization_admin` and `is_admin`, but it’s not clear what each of these are for. Can we stop using `is_admin`?

**Comment by AndrewKvalheim** [comment]
No, organization admins and site admins are [intended](https://github.com/openSUSE/osem/issues/1514) to be distinct.

**Comment by strugee** [comment]
Clearly there's room for better docs here tho?

**Comment by AndrewKvalheim** [comment]
Very much so; openSUSE/osem#1548
