### ISSUE TITLE
New repo to archive outreach materials

### ISSUE THREAD

**Issue by mateuskrause** [SeaGL/organization#294]
All the archived materials used in outreach (social media, print files, etc) are stored in this repository. Since it's using a significant amount of space here, we discussed at the last outreach meeting to move into a specific repository.

**Comment by altsalt** [comment]
@AndrewKvalheim is this something you'd be able to help with (if @mateuskrause is alright with that)? Specifically, I'm thinking that we want to remove the materials from this repository's history to address the storage concerns.

Hopefully the new repo will live under something like SeaGL/outreach to match the not-yet-pattern for committees that need their own repos.

**Comment by AndrewKvalheim** [comment]
Something like this?

- [SeaGL/organization/promotion_outreach](https://github.com/SeaGL/organization/tree/main/promotion_outreach) 74→0 MB
    - ~~`/design`~~: Move to SeaGL/outreach
    - `/README.md`: Add link to SeaGL/outreach, remove link to Google Drive
    - `/social_guide.md`
    - `/social_schedule.md`
- [Google Drive](https://github.com/SeaGL/organization/blob/5ceb3764c774663a9a2a773bff98eb8c6440472e/promotion_outreach/README.md?plain=1#L3) 263→0 MB
    - ~~`/2021`~~: Move to SeaGL/outreach
    - ~~`/2022`~~: Move to SeaGL/outreach
    - ~~`/Profile Banner`~~: Move to SeaGL/outreach
    - ~~`/Style Guide`~~: Move to SeaGL/outreach
- [SeaGL/outreach](https://github.com/SeaGL/outreach) 0→337 MB
    - `/2021`: Moved from Google Drive
    - `/2022`: Moved from Google Drive
    - `/design`: Moved from SeaGL/organization/promotion_outreach
    - `/Profile Banner`: Moved from Google Drive
    - `/Style Guide`: Moved from Google Drive
    - `/README.md`: Create

I can take care of the version history preservation, cleanup, etc.

**Comment by altsalt** [comment]
That looks right to me. @mateuskrause ? Also, is there's any reason to keep the Google Drive files there, guessing not but figured its worth asking explicitly.

**Comment by mateuskrause** [comment]
This looks good to me too. I would only ask not to remove or add the Google Drive files to the repo yet, as I would like to reorganize them before archiving.

**Comment by AndrewKvalheim** [comment]
Creation of `SeaGL/outreach`:

```console
$ git clone 'git@github.com:SeaGL/organization.git' --origin 'SeaGL' 'outreach'
Cloning into 'outreach'...
remote: Enumerating objects: 1438, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 1438 (delta 80), reused 25 (delta 12), pack-reused 1328
Receiving objects: 100% (1438/1438), 51.73 MiB | 5.13 MiB/s, done.
Resolving deltas: 100% (715/715), done.
$ cd 'outreach'
$ git filter-repo --path-rename 'promotion_outreach/:' --path 'promotion_outreach/design'
Parsed 247 commits
New history written in 0.05 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
HEAD is now at 3f79212 Merge pull request #247 from mateuskrause/design
Enumerating objects: 319, done.
Counting objects: 100% (319/319), done.
Delta compression using up to 16 threads
Compressing objects: 100% (250/250), done.
Writing objects: 100% (319/319), done.
Total 319 (delta 65), reused 312 (delta 65), pack-reused 0
Completely finished after 0.47 seconds.
$ git remote set-url 'SeaGL' 'https://github.com/SeaGL/outreach.git'
$ git add 'README.md'
$ git commit
[main 5e62002] Document repository
 1 file changed, 5 insertions(+)
 create mode 100644 README.md
$ git push
Enumerating objects: 322, done.
Counting objects: 100% (322/322), done.
Delta compression using up to 16 threads
Compressing objects: 100% (253/253), done.
Writing objects: 100% (322/322), 51.00 MiB | 8.37 MiB/s, done.
Total 322 (delta 65), reused 319 (delta 65), pack-reused 0
remote: Resolving deltas: 100% (65/65), done.
To github.com:SeaGL/outreach.git
 * [new branch]      main -> main
```

Revision of `SeaGL/organization`:

```console
$ git clone 'git@github.com:SeaGL/organization.git' --origin 'SeaGL' 'organization'
Cloning into 'organization'...
remote: Enumerating objects: 1438, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 1438 (delta 80), reused 25 (delta 12), pack-reused 1328
Receiving objects: 100% (1438/1438), 51.73 MiB | 21.99 MiB/s, done.
Resolving deltas: 100% (715/715), done.
$ cd 'organization'
$ git filter-repo --invert-paths --path 'promotion_outreach/design'
Parsed 247 commits
New history written in 0.05 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
HEAD is now at bc81d46 Merge pull request #289 from SeaGL/NormanGross-finance-20220620
Enumerating objects: 1114, done.
Counting objects: 100% (1114/1114), done.
Delta compression using up to 16 threads
Compressing objects: 100% (442/442), done.
Writing objects: 100% (1114/1114), done.
Total 1114 (delta 642), reused 1113 (delta 641), pack-reused 0
Completely finished after 0.15 seconds.
$ git add 'promotion_outreach/README.md'
$ git commit
[main b643ae4] Link to SeaGL/outreach repository
 1 file changed, 2 insertions(+)
$ git push --force
Enumerating objects: 1110, done.
Counting objects: 100% (1110/1110), done.
Delta compression using up to 16 threads
Compressing objects: 100% (444/444), done.
Writing objects: 100% (1110/1110), 708.11 KiB | 10.26 MiB/s, done.
Total 1110 (delta 639), reused 1102 (delta 635), pack-reused 0
remote: Resolving deltas: 100% (639/639), done.
To github.com:SeaGL/organization.git
 + c43400b...b643ae4 main -> main (forced update)
```
