### ISSUE TITLE
Set up conference table/kiosk laptop

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#299]
SeaGL’s HP Chromebook 14 was factory reset prior to our migration [off of Google Workspace](https://github.com/SeaGL/organization/issues/239). Before we can use it, we need to either:

- Create a dedicated Google account ([without Gmail](https://support.google.com/accounts/answer/27441?hl=en#existingemail)) matching the credentials printed on the bottom of the laptop for use with ChromeOS.
- [Install](https://wiki.debian.org/InstallingDebianOn/HP/Chromebook%2014) an alternative operating system such as Debian.

In either case the laptop will need to be configured for conference table/kiosk use.

**Comment by altsalt** [comment]
Do we need to do any of these steps before removing the previous Google account?

**Comment by AndrewKvalheim** [comment]
No; this issue is only the steps necessary for when we next want to use the laptop.

**Comment by AndrewKvalheim** [comment]
We’ve been successfully using just the guest account.
