### ISSUE TITLE
SeaGL 2022 gifts and per diem

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#321]
# Request information

Name: Wm Salt Hale
Date of purchase/expenditure: 2022-10-25
Description: $780 for toe socks and $40 for two days of lunch
Reimbursement amount: $820
Where the receipt is (e.g. "such-and-such a folder in Google Drive/Nextcloud"; please redact sensitive info): https://drive.google.com/drive/folders/1_i4tsR8D73p7ttU5cu6wHcZIiTxFy246

- [x] I've added a label for my committee in addition to the "Finance" label. If you don't have GitHub permissions to do this, leave this box unchecked.

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by NormanGross** [comment]
With Salt's permission, listing this as completed.
