### ISSUE TITLE
Upgrade the last few Matrix rooms

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#332]

**Comment by AndrewKvalheim** [comment]
When this is complete, [enable](https://github.com/SeaGL/patch/blob/16968410b6be5e39aff71b9610628e4a9463f69c/src/lib/Reconciler.ts#L152) `knock_restricted` in Patch.

**Comment by strugee** [comment]
What's our timing here given the CFP launch?

**Comment by AndrewKvalheim** [comment]
[What’s left](https://github.com/SeaGL/patch/blob/270055ab290af5b62cb09ede55e9ff8da4290cef/upgrade#L165-L170) is:

- Announcements
- General Discussions
- Participate
- All Staff Discussions
- Programming & Flow Committee

and I assume [Office Hours](https://github.com/SeaGL/organization/issues/288) again, so the earlier the better to minimize interruption.

**Comment by AndrewKvalheim** [comment]
Down to just All Staff. Several active threads there related to launching the CFP so I’ll wait for that first.
