### ISSUE TITLE
decide whether seagl will be signing the publichealthpledge

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#353]
https://publichealthpledge.com/

https://floss.social/@phpledge/109905262569278801

Salt wants this open for a couple weeks of discussion

We will target a decision in mid-April

Anything we require, we'll need to provide (e.g., masks)

Will need to work out phrasing for questions about things like vaccination and mask use based on how service questions are best asked

Good idea to review what disability twitter has discussed regarding this

**Comment by lufthans** [comment]
A published and enforced health policy is a key factor for accessibility.

Within the FLOSS community we have people with long COVID and other immune system compromising health issues.

Remote attending options are not sufficient for accessibility.

PHPledge is asking for

* A public health policy that will not be weakened going into the event. It can be strengthened
* Disclosure of policy in the useful places ( that we would already generally endeavor to do )
* "The event’s policy includes active measures designed to minimize the number of participants who are infected with transmissible diseases like COVID-19, as well as mitigate transmission between participants."

Quoted the last one to make sure I don't exclude one of the parameters.

**Comment by brettsheffield** [comment]
Thanks for raising this Salt. I agree with @lufthans points.

As a former speaker at SeaGL and someone who'd like to attend again, I'd encourage you to sign the Public Health Pledge both as an individual and as SeaGL.

Read the three things the PublicHealthPledge asks (see lufthans comment). If you're *not* signing, I'd ask you to think hard about which of these three points you object to. Having a clear health policy? Publishing it? Or taking basic steps to protect both your attendees, speakers and anyone they come into contact with?

FOSS is about community. Lets not put that community at risk unecessarily.

And lets be clear. No one is forcing anyone to wear a mask. If anyone doesn't feel comfortable wearing one, or complying with the other health requirements (or the CoC for that matter), there's always the option to stay home and watch the recorded/streamed talks from the comfort of their armchair.

I've had Long Covid now for three years, and I assure you it's not a lot of fun. I made a video for Long Covid Awareness Day last month with a plea to event organisers [here](https://www.youtube.com/watch?v=96qKdqVQgeg).

I know there are some folks who like to study the numbers and make their own risk assessments. Great. You have that right. But you don't have the right to make that risk assessment for everyone else, which is what you're doing when you wont take precautions against a virus that you can catch and spread and not even be aware of it. This is about consent, and you can't give that consent on behalf of another.

**Comment by jillr** [comment]
I've only participated in a couple virtual SeaGL's but I'm an individual signer to the PHP.  I look at events having a robust public health policy in the COVID era (and eventually, beyond) as equivalent to having a Code of Conduct - the bare minimum to truly ensure that everyone can participate equally and equitably regardless of personal health and capacity for risk.

We can do better by our communities than saying that risking COVID or the old days of "con crud" is the price of participation.  Fully support SeaGL signing the PHP.

**Comment by AndrewKvalheim** [comment]
The only thing that gives me pause is the ratchet. Why prohibit well-intentioned corrections to the policy if an early version had a mistake?

As written the pledge disincentivizes adoption of an appropriately strong policy by making perfect the enemy of good.

**Comment by brettsheffield** [comment]
Andrew,

There's no problem with corrections to a policy, only that the policy cannot be weakened between when the event is announced and when it is held. This is so that anyone who makes preparations to attend (transport, accommodation, time off work etc.) knows that the health standards will be *at least* as high as they were at the time they committed.

**Comment by brettsheffield** [comment]
An excellent example of a Covid-safe event policy from AUC:

[https://auc.edu.au/policies/covid-safe-plan/](https://auc.edu.au/policies/covid-safe-plan/)

**Comment by joshsimmons** [comment]
I really appreciate how thoughtful and proactive y'all are being about this aspect of SeaGL! It's great that this is being discussed now well ahead of the CFP.

A few thoughts as a fellow organizer and as author of the Public Health Pledge which may be useful:

* Mask mandate is the single most powerful and cost effective precaution you can put in place.
* Lower density seating (either by moving things or blocking some things off) is also a cost effective approach to mitigating spread.
* Lunch, tea/snack breaks, and receptions are the riskiest settings – maximize use of outdoors (tho recognizing this is in fall in Seattle, that may not be possible), consider takeaway containers, and try to put healthy distance between distribution (where people can remain masked) and consumption (where people are necessarily not masked).
* Older venues tend to have poor indoor air quality, so consider renting air purifiers or cobbling together Corsi-Rosenthal boxes for session rooms.
* Recommend vaccines and daily testing, even if you can't provide those things, and provide guidance on where people can get tests.
* Offer rapid tests gratis to people – attendees and speakers – who are receiving financial aid.
* Offer live streaming so folks who wake up feeling snuffly or otherwise off don't feel like they need to show up or risk missing out.

I _suspect_ y'all could manage "Robust Policy" on masking and at least "Efforts Made" on the other elements of the PHPledge badging standard.

Happy to be a resource or sounding board as you think these things through!

**Comment by vagrantc** [comment]
Would love to see SeaGL adopt the publichealthpledge and relevent policies and practices ... it would save a lot of stress about weather to submit talk proposals and/or attend an event I have definitely valued over the years!

**Comment by joshsimmons** [comment]
Sharing a resource from SeaGL's unofficial sister conference North Bay Python <3 We just published our Health and Safety policy after completing legal review. Some of it is definitely specific to the venue we're operating in, but nonetheless may be a useful source of inspiration: https://2023.northbaypython.org/health-and-safety-policy

**Comment by joshsimmons** [comment]
Following up, I see the CFP has been launched without a Health and Safety policy. Is there an update on where the organizing team is at on this matter?

Launching a CFP without a baseline H&S policy puts prospective speakers in a tough spot.

**Comment by lufthans** [comment]
( speaking as self, not for SeaGL )

First, thanks to everyone for the feedback and suggestions!

We wanted to get the cfp out extra early this year ( thanks to the organizing committee for the extra effort on that! ), which was before we started considering the the Public Health Pledge ( I think I had brought it up, but we hadn't yet started the conversation ).

I believe ( again, speaking for me not for SeaGL ) it is critical to have our health policy announced before the cfp closes.

We do have some hurdles to overcome before we can commit to a policy. My primary concern for now is that we will be moving to a new facility that we haven't worked with before. We need to understand the space available and also what we can effectively enforce.

Facility guidelines might not allow us to enforce the policy we want. Also, SeaGL will be in a shared physical space available to the public which limits what we can effectively enforce.

I want us to have a policy that matches the Public Health Pledge and for us to sign the pledge.

**Comment by brettsheffield** [comment]
Thanks lufthans.

SeaGL seems to be considering the matter, if I may use an Australian term here, _arse-about_. 

Surely if the venue can't support your (SeaGL's) desired health policy, then the venue is unsuitable for the event?

If it had no wheelchair access, would the event still be suitable?

If the venue made it impossible to enforce aspects of the SeaGL CoC, would the venue still be suitable?

You see what I'm getting at here? If we have principles, like a CoC or a Health policy, we need to commit to that and fight for it. Principles aren't always convenient - surely Free Software has taught us that much!

If you have decided (I hope!) that you care about protecting the health of participants, then surely that isn't something that can be compromised upon? If the venue is unsuitable, another must be sought. If no other venue is available, the conference needs to be virtual-only again.

This is why the Health policy needs to come first - *before* choosing a venue or deciding to run an in-person event.

In the end it's up to you good folks to decide as the organisers, but if you proceed with a weakened Health policy that puts participants at risk, that is an active choice you are making, not the venue.

**Comment by altsalt** [comment]
Thank you all for taking the time to provide your thoughts on the importance of a Health and Safety Policy. I've been reading these, and ones shared in other venues, and just uploaded a first-draft of our [2023 policy](https://github.com/SeaGL/seagl.github.io/pull/392).

If possible, we'd love to have your feedback on this draft before discussing it at our next all-staff meeting on May 15 (which you are more than welcome to attend of course).

I won't respond to everything said in this thread, but do want to stress that SeaGL is a grass-roots, volunteer-run, free-to-attend event. Our needs and resources likely differ from many other conferences. Hopefully the policies written address everyone's concerns while avoiding an undue burden on our staff.

Once again, thank you all for your time and attention to this topic!

**Comment by tinkerwilco** [comment]
It is an open question on how this volunteer-run event will enforce CoC violations, including those in the health pledge. We can make it known that someone is unwelcome, but we don't really have the ability to physically bar people from entering our area in the public spaces on campus. This is not keeping us from submitting the pledge, but we need to have some discussions about this in general so we have it documented somewhere what we are willing to do and how it can be done.

**Comment by altsalt** [comment]
We have released our [Health and Safety Policy](https://seagl.org/health_and_safety_policy) and submitted to the Public Health Pledge badging. Closing this issue as complete. Another one will be opened for subsequent tasks.
