### ISSUE TITLE
Allow programmatic IMAP access to DMARC reports

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#358]
I got as far as this screen but don’t know how to proceed:

> <img src="https://user-images.githubusercontent.com/1844746/233466304-11b02261-177d-4cd7-9229-e15c75c06e12.png" alt="Google Account / App passwords / The setting you are looking for is not available for your account." width="960" />

blocking #265

**Comment by altsalt** [comment]
Is this something I can help with? I see a few entries in [App access control](https://admin.google.com/ac/owl/list?tab=apps) but am not quite sure what you're looking for.

**Comment by AndrewKvalheim** [comment]
I want to automate access to this mailbox via IMAP. Last time I used Gmail the way to do that was to create an application-specific password that could be used in automated authentication. I don’t know why it’s “not available” here with no further comment. Maybe Google wants people to solve this problem differently now?

**Comment by AndrewKvalheim** [comment]
Google [says](https://support.google.com/mail/answer/7126229) to just use the user’s password:

> Password: Your Gmail password
