### ISSUE TITLE
write thank you for attending blog post

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#36]
Rachel and Salt had their names next to this, but anyone is welcome to help lead the charge!

- [ ] include number of unique nicks the bot saw
- [ ] include sponsor call outs
- [ ] get final "attendance numbers" e.g. unique nicks, etc
    - IRC room counts: https://andrew.kvalhe.im/+e1mb787nbriqupxtach6bcgz8pcztfda

**Comment by funnelfiasco** [comment]
Since we're pretty far past the end of SeaGL 2020, is it still worth doing this?

**Comment by altsalt** [comment]
I think that's worth discussing at Monday's meeting. Seems like it might be nice to have, but I agree with the incurred time debt.

**Comment by funnelfiasco** [comment]
We agreed in the meeting that we should skip this.
