### ISSUE TITLE
Set up BorgBase

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#364]
At a minimum this means provisioning an account and setting settings on it, then putting the creds in 1Password. But probably we also want to do some stuff with Ansible to actually turn on backups on servers. Unclear as to exactly what that would look like.

**Comment by altsalt** [comment]
This definitely seems worthwhile. I've recently gone with [borgmatic](https://torsion.org/borgmatic/) as a personal backup solution.

**Comment by strugee** [comment]
Blocker for #341

**Comment by altsalt** [comment]
This seems like it could be a fairly encapsulated hacktoberfest project if we were trying to do that.

**Comment by strugee** [comment]
Hmm. Maybe? Unclear as to how much prod access you need though

**Comment by altsalt** [comment]
Yeah, uncertain either. I mean I was imagining the script is setup and ready to deploy but we'd fill in the BorgBase repo uri and set of directories that need to be backed up.

**Comment by strugee** [comment]
Right. I mean we'd probably just pull an Ansible role... so I guess in theory you could fully develop against a VM? And just make another BorgBase account to test?

**Comment by altsalt** [comment]
Right, but again, it is something we could do, but would probably be reasonably encapsulated for a drive by contributor.

**Comment by strugee** [comment]
Right, https://github.com/SeaGL/organization/issues/364#issuecomment-1744194092 was me convincing myself that this can be reasonably done by an external contributor lol
