### ISSUE TITLE
Inability to join Matrix rooms via `seagl.org` aliases

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#368]
We’ve received reports ([example](https://josh.tel/@josh/110532395236772579)) of vague error messages when people try to join Matrix rooms via the [`seagl.org` aliases](https://github.com/SeaGL/organization/issues/286).

### Reproduction

When trying to join `#test-2023-06-13:seagl.org`, Synapse logs:

```
Request failed: PUT matrix://seagl.org/_matrix/federation/v1/send/1685687770792: HttpResponseException('404: Not Found')
Request failed: GET matrix://seagl.org/_matrix/federation/v1/make_join/%21rvWybNVXTWAXMIVoCW%3Aseattlematrix.org/…: HttpResponseException('404: Not Found')
Request failed: PUT matrix://seagl.org/_matrix/federation/v1/send/1685687770793: HttpResponseException('404: Not Found')
```

Synapse correctly resolved the alias to a room ID—it successfully followed the [delegation](https://seagl.org/.well-known/matrix/server) and queried [the proxy](https://alias.seagl.org/_matrix/federation/v1/query/directory?room_alias=%23test-2023-06-13%3Aseagl.org)—yet still it tried to federate with a nonexistent endpoint.

**Comment by AndrewKvalheim** [comment]
@‌tulir identified that this is likely due to Synapse unconditionally [adding](https://github.com/matrix-org/synapse/blob/v1.85.2/synapse/handlers/room_member.py#L1501) a `seagl.org` homeserver to the proxy’s response, has [proposed](https://github.com/matrix-org/synapse/pull/15776) the removal of that behavior from future versions of Synapse, and [updated](https://github.com/tulir/mauliasproxy/releases/tag/v1.1.0) mauliasproxy to work around the issue with existing Synapse versions.

**Comment by altsalt** [comment]
The proposed change was merged, dunno when it will make it into the ansible project.

**Comment by strugee** [comment]
Doesn't matter - we might have Debian stable users. We need to deploy the updates to the alias that work around stuff for old Synapse versions.

**Comment by AndrewKvalheim** [comment]
See also @‌csett86’s [Synapse adoption graphs](https://matrix.org/blog/2020/06/19/this-week-in-matrix-2020-06-19#synapse-adoption-graphs)

> ![screenshot](https://github.com/SeaGL/organization/assets/1844746/7ca911f2-18c6-45e8-8153-ce5fdb635c39)
