### ISSUE TITLE
2023 FOSSlive newsletter CFP graphics

### ISSUE THREAD

**Issue by lufthans** [SeaGL/organization#371]
They prefer png or jpg.

We might be able to get a hit in the newsletter this week.

600x110
300x250

After that, we would adjust the images to whatever we want to hit next, e.g. announcing location or keynotes.

This is likely 2nd highest priority for the sponsorship committee as they can toss our ads in when they have space.

**Comment by altsalt** [comment]
Done, assets in https://github.com/SeaGL/outreach/tree/main/design/ads/newsletter/2023
