### ISSUE TITLE
2023 Linux Magazine site ads

### ISSUE THREAD

**Issue by lufthans** [SeaGL/organization#372]
They prefer png or jpg.

We can get ads on the Linux Magazine site.

Static or animated images under 1MB in size.

728x90
300x250
160x600

Let's start with announcing basics of conference with a space for the tagline of the time, e.g. location announcement, keynotes,  etc.

This is likely highest priority for the sponsorship committee as they can toss our ads up once we get them over.

**Comment by altsalt** [comment]
Done, assets can be found in https://github.com/SeaGL/outreach/tree/main/design/ads/website/2023
