### ISSUE TITLE
Keynote travel reimbursement: Hong Phuc Dang

### ISSUE THREAD

**Issue by lufthans** [SeaGL/organization#385]
# Request information

Name: Hong Phuc Dang
Date of purchase/expenditure: 2023-10-02
Description: flight and hotel
Reimbursement amount: US$1,392.23 ( US$906.70 flight + US$485.53 hotel )
Where the receipt is (e.g. "such-and-such a folder in Google Drive/Nextcloud"; please redact sensitive info): receipts per email

- [x] I've added a label for my committee in addition to the "Finance" label. If you don't have GitHub permissions to do this, leave this box unchecked.

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by NormanGross** [comment]
Spreadsheet entry created and updated.  Ready to review in finance meeting.   May need address of requester.

**Comment by NormanGross** [comment]
Request turned in to OSI
