### ISSUE TITLE
Reimbursement: 2023 Jitsi server

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#396]
# Request information

Name: AJ Jordan
Date of purchase/expenditure: November 2023
Description: the Jitsi server we used for social events this year. Honestly I wouldn't even bother requesting reimbursement if #395 wasn't already going out.
Reimbursement amount: $3.06
Where the receipt is (e.g. "such-and-such a folder in Google Drive/Nextcloud"; please redact sensitive info): https://cloud.seagl.org/index.php/f/4709 (internal-only link) - [like last year](https://github.com/SeaGL/organization/issues/328#issuecomment-1452575657) I've redacted unrelated stuff, so ~$3 is the correct amount.

- [x] I've added a label for my committee in addition to the "Finance" label. If you don't have GitHub permissions to do this, leave this box unchecked.

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by strugee** [comment]
For this issue and #395, a check to the address listed on the invoices is fine. USD.

**Comment by NormanGross** [comment]
Thank you for the comment about a check.

**Comment by NormanGross** [comment]
Request sent to OSI
