### ISSUE TITLE
Select SeaGL 2024 Theme

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#398]
Please add suggestions for the SeaGL 2024 theme, which is going to be year 12.

It would be nice to select this in time for inclusion in the Save the Date announcement.

**Comment by AlfredoMS** [comment]
More on 12: https://en.wikipedia.org/wiki/12_(number)

**Comment by altsalt** [comment]
And more on the numeric side of things: https://en.wikipedia.org/wiki/Duodecimal

**Comment by altsalt** [comment]
Some random brainstorming:

SeaGL 2024: "See a dozen gull eggs"
SeaGL 2024: "A most abundant year"
SeaGL 2024: "Duodecimal Decade"
SeaGL 2024: "Last of the pre-teen years"
SeaGL 2024: "Flying around the clock"
SeaGL 2024: "Marking off the months"
SeaGL 2024: "A dozen down"

**Comment by AlfredoMS** [comment]
brainstorming:

SeaGL 2024: "Full circle"
SeaGL 2024: "Around the clock"
SeaGL 2024: "Tech Zodiac"

**Comment by strugee** [comment]
SeaGL 2024: "No Leap Seconds!"

(or something like that?)

**Comment by strugee** [comment]
SeaGL 2024: "Maximum (Sailboat) Speed"

**Comment by altsalt** [comment]
SeaGL 2024: "High Noon"

**Comment by altsalt** [comment]
SeaGL 2024: "Clock strikes midnight on proprietary software"

**Comment by AlfredoMS** [comment]
"Around the clock" has won the popular vote within the staff.

Closing issue.

**Comment by AlfredoMS** [comment]
Results from starvote:

<div>8 voters</div>
			
# | Option | Points | Average
-- | -- | -- | --
1 | Around the clock | 30 | 3.8
75.0% (3.8/5)
2 | Duodecimal Decade | 21 | 2.6
52.5% (2.6/5)
3 | Flying around the clock | 21 | 2.6
52.5% (2.6/5)
4 | High Noon | 21 | 2.6
52.5% (2.6/5)
5 | The clock strikes midnight on proprietary software | 21 | 2.6
52.5% (2.6/5)
6 | Duodisseminating Knowledge | 18 | 2.3
45.0% (2.3/5)
7 | A most abundant year | 17 | 2.1
42.5% (2.1/5)
8 | Full circle | 16 | 2.0
40.0% (2.0/5)
9 | Marking off the months | 15 | 1.9
37.5% (1.9/5)
10 | A dozen down | 15 | 1.9
37.5% (1.9/5)
11 | A dozen gull eggs | 14 | 1.8
35.0% (1.8/5)
12 | Last of the pre-teen years | 10 | 1.3
25.0% (1.3/5)
13 | No Leap Seconds! | 10 | 1.3
25.0% (1.3/5)
14 | Max Sail Speed | 10 | 1.3
25.0% (1.3/5)
15 | Tech Zodiac | 9 | 1.1
22.5% (1.1/5)
16 | Almost a Teenager | 9 | 1.1
