### ISSUE TITLE
confirm whether art dept made 4:3 pandemic seagl logo for videos

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#40]

**Comment by funnelfiasco** [comment]
@altsalt We have 4:3 title cards in https://drive.google.com/drive/u/1/folders/1WUJXvTRCITuPRNAhr0P5C1jEZbgwg8-x
Let me know if that's not what you need

**Comment by altsalt** [comment]
It looks like this was taken care of, since the videos were pressed with the logo. Thanks!
