### ISSUE TITLE
save-the-date fliers

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#405]
# Request information

Name: Salt
Date of purchase/expenditure: 2024-04-06 and 2024-04-16
Description: printing of save-the-date fliers
Reimbursement amount: $43.60
Where the receipt is (e.g. "such-and-such a folder in Google Drive/Nextcloud"; please redact sensitive info): two receipts in https://cloud.seagl.org/index.php/f/8114

- [x] I've added a label for my committee in addition to the "Finance" label. If you don't have GitHub permissions to do this, leave this box unchecked.

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by NormanGross** [comment]
Please verify that the form is filled out correctly for payment information and sign.

https://docs.google.com/spreadsheets/d/1RlEN2P5sz099CLENWSDfRJu7vmpw9ppZATnvt0ahRH4/edit#gid=1740401096

**Comment by NormanGross** [comment]
Sent to OSI.

**Comment by altsalt** [comment]
Received via PayPal on 2024-06-05
