### ISSUE TITLE
Reimbursement: Equipment bags, cable ties

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#422]
# Request information

Name: Andrew
Date of purchase/expenditure: 2024-10-29
Description: 2 equipment bags, 70 cable ties
Reimbursement amount: $38.65
Where the receipt is: [/SeaGL/Finance/reimbursement_requests/2024/2024-10-29 Andrew · Equipment bags, cable ties.pdf](https://cloud.seagl.org/index.php/f/40577)

- [x] I've added a label for my committee in addition to the "Finance" label. If you don't have GitHub permissions to do this, leave this box unchecked.

# Financial committee 

- [x] Request acknowledged
- [x] Request reviewed
  - [x] Approved
  - [ ] Denied
  - [ ] Needs more information
- [x] Request sent to OSI
- [x] Reimbursement issued
- [x] [REQUESTER] Reimbursement received and issue closed

**Comment by NormanGross** [comment]
Request sent to OSI.

**Comment by NormanGross** [comment]
OSI issued reimbursement on Dec 6th

**Comment by AndrewKvalheim** [comment]
Received, thanks!
