### ISSUE TITLE
upload 2020 videos to archive.org (and elsewhere?)

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#45]
blocked by #44

**Comment by AndrewKvalheim** [comment]
Our initial choice of upload tooling resulted in the videos being regarded by the Internet Archive as principally an unauthorized mirror of YouTube, falling subject to bibanon/tubeup#101. Internet Archive staff have recommended re-uploading them without reference to YouTube.

**Comment by AndrewKvalheim** [comment]
Moving the videos out of [Mirrortube](https://archive.org/details/archiveteam_youtube) and into the newly created [SeaGL collection](https://archive.org/details/seagl) resolved the problem of automated suppression.

The video identifiers still prominently referenced YouTube, and Internet Archive denied our request for an exemption to its policy of no longer modifying identifiers, so we’ve re-uploaded the videos with human-meaningful identifiers using [`ia`](https://archive.org/services/docs/api/internetarchive/cli.html) and deleted the `tubeup`-uploaded videos.

The videos are now ready at [SeaGL → 2020](https://archive.org/details/seagl?and[]=year%3A%222020%22).
