### ISSUE TITLE
Linux Magazine newsletter ads

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#60]
We have two newsletters available for trade partners -- Linux Update and ADMIN Update. The newsletters are released on Wednesdays and alternative each week. The next Linux Update is on April 14th. I can offer you 4 newsletter ads in any of the following sizes (as space is available):
728x90 static image
300x250 static image
Text Ad: 3-5 world headline, up to 50 words, call to action with link

We can go with a single image and I'll update the CTA as needed for the different phases of the ad campaign

**Comment by mateuskrause** [comment]
As they have the same sizes as the website ads (#59) I used the same phrases and designs. ([draft](https://gnu-cloud.yourownnet.cloud/s/SXjcZ5pZrojEKbA?dir=undefined&path=%2FSeaGL_2021%2Fads&openfile=120150))

One problem is that the ones with size 728x90 don't have an action link. Since it's a newsletter, would be interesting to add the links, even having to make some changes because of space?

**Comment by mateuskrause** [comment]
I exported to png and uploaded the above drafts. They are on Google Drive at `Outreach/2021/ads/newsletter_ads/png`.

**Comment by funnelfiasco** [comment]
In today's meeting, @mateuskrause agreed to send these to Linux  Pro Magazine

**Comment by mateuskrause** [comment]
@funnelfiasco last time when you sent the website ads, do you specified when to use each one? We have the volunteers and conference call versions, maybe we can start with the volunteers until one specified date and after start the conference call ones.

**Comment by funnelfiasco** [comment]
No, they just used them in rotation. Your idea sounds good, though.

**Comment by mateuskrause** [comment]
Ok. I'll specify that the last ad before the conference has to be the conference call, the others rotate is a good option.

**Comment by mateuskrause** [comment]
We've got an answer from Gwen and the newsletters have been sold out for the last month, but they will fit in the ones we sent where they can.
