### ISSUE TITLE
Write email to SeaGL announce list

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#71]
Write email to SeaGL announce list that includes: "save the date", "CFP open", "we're virtual this year", and "still need volunteer help, especially..."

**Comment by funnelfiasco** [comment]
First draft available on the [Seattle Matrix etherpad](https://etherpad.seattlematrix.org/p/SeaGL_2021_announce). Comments welcome.

Still waiting for:

* Prospectus (#110)
* Volunteers wanted blog post (#55 )

**Comment by funnelfiasco** [comment]
The pad lost my draft, so I made a [new one](https://etherpad.seattlematrix.org/p/SeaGL_2021_announce). I'll send it after today's Outreach meeting, so if you have edits, please suggest them soon!

**Comment by funnelfiasco** [comment]
[Sent](https://groups.google.com/g/seagl_announce/c/jG7cKWKTW1o)

**Comment by altsalt** [comment]
Btw, might want to send this to seagl_organize@googlegroups.com as well, I really need to clear up the email ratsnest,,,

**Comment by funnelfiasco** [comment]
Sent to seagl_organize
