### ISSUE TITLE
Flesh out 2021 timeline

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#85]
- May 10 (Monday)*: Keynote nominations open
- May 24 (at the earliest): Keynote nominations close
- June 15 (Tuesday)**: CFP opens
- August 5 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

**Comment by altsalt** [comment]
Rachel and Nathan's initial pass: https://docs.google.com/spreadsheets/d/1Za_uEHQVXir3kHXFOVM3htwgmQ6YFJ0a1R1HP-dNYFs/edit#gid=0

**Comment by altsalt** [comment]
I've added it to the meeting sheet, will leave the issue open, at least until the next meeting, so we can see whether there are additions to make. [Here was the latest one from last year](https://github.com/SeaGL/organization/blob/master/meetings/2020/20201109-allhands.md#timeline), which might help inform anything to add.

**Comment by koronkowy** [comment]
We can probably close this, given.. we've made it all the way to week before.
